### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by mpaolo** [eriklins/InsideBlue-BLE-Tool#11]
Hi,

trying on win32-10 got the error in title on 'scan' - pls see attached screenshot - then it closes in few secs on its own. Also as admin.
Any clue?

thanx

PS: pity ble-scout binary is win64 only else I'd try it
![insideblue](https://github.com/user-attachments/assets/fce58975-1b81-41d5-a261-0c2d5e861777)

**Comment by eriklins** [comment]
Never came across this so far. I no longer have a win32 machine, so cannot check. And since I never got InsideBlue running properly on win64 (see #8 ) with Lazarus/Freepascal and SimpleBLE lib, I stopped working on InsideBlue and rewrote everthing in C, see https://github.com/eriklins/BLE-Scout. However, never tried this on win32 and hence no precompiled release available yet.

**Comment by mpaolo** [comment]
ok thx
